### ISSUE TITLE
Performance of Involvements for Divisions Query

### ISSUE THREAD

**Issue by jlawler-cis** [TenthPres/TouchPoint-WP#89]
On large client databases the existing "Involvements for divisions" query can encounter extremely long run times and was causing performance issues for other clients. I've resolved this issue by restructuring the query, moving the aggregate sub-queries out of the select statement and into common table expressions and reducing the number of calls to the People table. If you'd like, I can submit a pull request for review with these changes.

**Comment by jkrrv** [comment]
(@jlawler-cis  Sorry--not sure why I missed the notification for this.)

I'm always interested in pull requests!  

Since these queries should mostly run overnight, I don't have much motivation to optimize here (and therefore, I'm closing the issue), but I'll gladly review/merge a PR.
